const courses = [
    // fill it with random names, but each should have different values for each key
    {   
        id: 1,
        title: "Computer Organization",
        code: "CS F211",
        instructors: ["Amit Kumar", "Rahul Agarwal"],
        institute: "IIITD",
        rating: 4.8,
        instructor_rating: 4.6,
        difficulty: "Low",     // Low, Medium, Hard, Extreme
        workload: "Low",        // Low, Medium, High, Extreme
        size: 600,
        average_grade: 8,
    },
    {
        id: 2,
        title: "Introduction to Programming",
        code: "CS F111",
        instructors: ["Pranav Kumar", "Parth Kumar"],
        institute: "IIITD",
        rating: 4.5,
        instructor_rating: 4.5,
        difficulty: "High",
        workload: "High",
        size: 600,
        average_grade: 9,
    },
    {
        id: 3,
        title: "Computer Networks",
        code: "CS F212",
        instructors: ["John Doe", "Gaurav Verma"],
        institute: "IIITD",
        rating: 4.5,
        instructor_rating: 4.5,
        difficulty: "Extreme",
        workload: "Medium",
        size: 600,
        average_grade: 8,
    },
    {
        id: 4,
        title: "Discrete Mathematics",
        code: "MTH F112",
        instructors: ["Rahul Agarwal", "Bhavesh Agarwal"],
        institute: "IIITD",
        rating: 4.1,
        instructor_rating: 4,
        difficulty: "Medium",
        workload: "Medium",
        size: 300,
        average_grade: 8,
    },
    {
        id: 5,
        title: "Data Structures and Algorithms",
        code: "MTH F213",
        instructors: ["Siddharth Agarwal", "Lakshay Agarwal"],
        institute: "IIITD",
        rating: 4.5,
        instructor_rating: 4.5,
        difficulty: "High",
        workload: "High",
        size: 600,
        average_grade: 6,
    },
    {
        id: 6,
        title: "Multivariable Calculus",
        code: "MTH F211",
        instructors: ["Nishant Arora", "Gaurav Verma"],
        institute: "IIITD",
        rating: 4.5,
        instructor_rating: 4.5,
        difficulty: "Extreme",
        workload: "Medium",
        size: 600,
        average_grade: 7,
    },
    {
        id: 7,
        title: "Linear Algebra",
        code: "MTH F212",
        instructors: ["Anirudh Verma", "Chirag Agarwal"],
        institute: "IIITD",
        rating: 4.1,
        instructor_rating: 4,
        difficulty: "Medium",
        workload: "Medium",
        size: 300,
        average_grade: 7,
    },
    {
        id: 8,
        title: "Sociological Theory",
        code: "SSH F211",
        instructors: ["Siddharth Agarwal", "Lakshay Agarwal"],
        institute: "IIITD",
        rating: 4.5,
        instructor_rating: 4.5,
        difficulty: "Low",
        workload: "Medium",
        size: 100,
        average_grade: 7,
    }
]

export default courses;